# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Publicar Imagem no Docker Hub

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DOCKERHUB_ENV
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # Passo 2: Login no Docker Hub
      # Este passo usa os segredos para autenticar. É aqui que o erro acontecia.
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} # Usamos o TOKEN como senha

      # Passo 3: Extrair metadados (tags)
      - name: Extrair metadados da imagem
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/minha-api-fastapi # Verifique se este nome está correto

      # Passo 4: Construir e empurrar a imagem
      - name: Construir e empurrar a imagem para o Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}